### ISSUE TITLE
EditText-fält

### ISSUE THREAD

**Issue by felixnorden** [felixnorden/coffeebreak#13]
Ersätta alla EditText med AppCompatEditText fält, för kompatibilitet med API 21

**Comment by ZLundqvist** [comment]
Löser det för TaskEdit

**Comment by felixnorden** [comment]
(Y) Elias sitter med resterande just nu

**Comment by ZLundqvist** [comment]
- [x] Fixat för TaskEditActivity

**Comment by felixnorden** [comment]
https://pastebin.com/MYMFGDsE
Lösning

**Comment by felixnorden** [comment]
Alternativ lösning: ViewSwitcher

**Comment by ZLundqvist** [comment]
Tid finns ej för detta. Nuvarande implementation fungerar.
