### ISSUE TITLE
All category efter edit task

### ISSUE THREAD

**Issue by felixnorden** [felixnorden/coffeebreak#14]
Vi kommer alltid tillbaka till All-category efter en task har ändrats

**Comment by ZLundqvist** [comment]
Detta är förmodligen på grund av när man går tillbaka från TaskEdit, körs onCreate() i mainactivity och den sätter nuvarande kategorin till All-category?

**Comment by felixnorden** [comment]
Japp, men vi sa att vi väntar med det, därför lade vi den Git Issues.
