### ISSUE TITLE
Flytta TaskEditPresenter referens

### ISSUE THREAD

**Issue by felixnorden** [felixnorden/coffeebreak#15]
Flytta TaskEditPresenter referensen till DelegatingPresenter istället för i MainPresenter

**Comment by felixnorden** [comment]
Se till så att allt skapande och dependencyinjection sker i DelegatingPresenter och hämta intent på fritt sätt genom metodanrop eller så till mainPresenter

**Comment by felixnorden** [comment]
Och ha med model i factoryn istället för injection kanske

**Comment by ZLundqvist** [comment]
Det verkar som om DelegatingPresenter är designad till att bara hålla en presenter, i detta fall MainPresenter? Tänker framförallt på hur den håller i en context som hör till MainPresenter.

**Comment by ZLundqvist** [comment]
Jag förstår inte riktigt hur DelegatingPresenter fungerar. Skulle du kunna refaktorera så att den kan, på ett smidigt sätt, hålla i en TaskEditPresenter? @felixnorden

**Comment by felixnorden** [comment]
Den har första context för att ladda in alla data.

Det finns en lista för alla presenters, när din aktivitet startas så skickar du en request: `RequestPresenterEvent(this)` som du implementerar för din context. I den skapar du din presenter genom factory och med model och din context som inparameter.

När din activitet kör onDestroy eller liknande för att signalera att den är klar, skickar din presenter ut  `RemovePresenterEvent(this)`  så tas den ur listan

**Comment by ZLundqvist** [comment]
Varför använder vi oss av events mellan presenters ens? Kan dem inte va direkt beroende av varandra?

**Comment by felixnorden** [comment]
inte cirkulärt, ska följa Top Down-principen, annars försvinner vitsen med delegerande presenter och relationerna typ

**Comment by felixnorden** [comment]
Förstår problemet i vad du troligtvis syftar på... blir svårt att slänga runt när inte en activity finns...
